### ISSUE TITLE
Webpages don't load on IOS

### ISSUE THREAD

**Issue by willvlad** [iampawan/FlutterWidgets#1]
Tried running WebView_example on Android and IOS. Android runs, but IOS stays blank, just the title appears, but the rest of the page never loads. Have you succeeded to run IOS on your machine?

`Launching lib/main.dart on iPhone X in debug mode...
Starting Xcode build...
Xcode build done.
Syncing files to device iPhone X...
flutter: WebViewState.shouldStart
flutter: WebViewState.startLoad
flutter: WebViewState.shouldStart.`

**Comment by iampawan** [comment]
Yes it works for me

**Comment by willvlad** [comment]
Still not for me, unfortunately, only on Android for some reason
